export default {
    ADD_ITEM: "TODOS/ADD_ITEM",
    LOAD_ITEMS_REQUEST: "TODOS/LOAD_ITEMS_REQUEST",
    LOAD_ITEMS_SUCCESS: "TODOS/LOAD_ITEMS_SUCCESS",
    LOAD_ITEMS_FAILURE: "TODOS/LOAD_ITEMS_FAILURE",
    DELETE_ITEM: "TODOS/DELETE_ITEM",
    CHANGE_TEXT: "TODOS/CHANGE_TEXT",

    SET_CURRENT_PAGE: "TODOS/SET_CURRENT_PAGE",
    CHANGE_COMPLETED: "TODOS/CHANGE_COMPLETED"
}