export default {
    SIGNUP_REQUEST: "AUTH/SIGNUP_REQUEST",
    SIGNUP_FAILURE: "AUTH/SIGNUP_FAILURE",
    SIGNUP_SUCCESS: "AUTH/SIGNUP_SUCCESS",

    SIGNIN: "AUTH/SIGNIN",
    AUTH_SUCCESS: "AUTH/AUTH_SUCCESS",
    AUTH_FAILURE: "AUTH/AUTH_FAILURE",
    LOGOUT: "AUTH/LOGOUT"
}